site_name: ZOO WES Runner
site_description: 'Zoo WES Runner'
# Repository

repo_name: 'eoepca/eoepca-zoo-wes-runner'
repo_url: 'https://github.com/EOEPCA/eoepca-zoo-wes-runner'
edit_uri: 'blob/main/docs/src/'
site_url: 'https://eoepca.github.io/eoepca-zoo-wes-runner/'


theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
  - mkdocs-jupyter

nav:
  - Introduction: 'index.md'
  - Installation: 'installation.md'
  - Getting started: 
    - toil settings: '01_configuring_toil.md'
    - Network settings: '02_configuring_ades.md'
  - Configuration: 'configuration.md'
  - API:
    - base: api/zoo_wes_runner/base.md
    - zoo_wes_runner: api/zoo_wes_runner/wes_runner.md
